agent_name = "pipecat-quarterzip"
image = "isischameleon/pipecat-demo-with-screensharing:0.1"
secret_set = "pipecat-demo-with-screensharing"
agent_profile = "agent-2x"
enable_krisp = true

[scaling]
	min_agents = 0
